version: 17
jobs:
- name: Test
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: run tests
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands:
      - just test
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  caches:
  - key: '@project_path@'
    path: target
  timeout: 3600
  postBuildActions:
  - !RunJobAction
    condition: successful
    jobName: Github Push
- name: Github Push
  steps:
  - !PushRepository
    name: Push to GitHub
    remoteUrl: https://github.com/jayson-lennon/pylon
    passwordSecret: github-sync
    withLfs: false
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
- name: GitHub Pull
  steps:
  - !PullRepository
    name: Pull from GitHub
    remoteUrl: https://github.com/jayson-lennon/pylon
    passwordSecret: github-sync
    refs: refs/heads/* refs/tags/*
    withLfs: false
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
