[package]
name = "typed_path"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0", features = ["std"] }
derivative = "2.2"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
temptree = "0.2.0"
tempfile = "3.3"