[package]
name = "pipeworks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "pipeworks"
path = "src/lib/pipeworks.rs"

[dependencies]
tempfile = "3.3.0"
regex = "1.5.5"
scraper = "0.12.0"